# Nightfox Wezterm Colors
# Style: nightfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/nightfox_wezterm.toml
[colors]
foreground = "#cdcecf"
background = "#192330"
cursor_bg = "#cdcecf"
cursor_border = "#cdcecf"
cursor_fg = "#192330"
selection_bg = "#283648"
selection_fg = "#cdcecf"
ansi = ["#393b44", "#c94f6d", "#81b29a", "#dbc074", "#719cd6", "#9d79d6", "#63cdcf", "#dfdfe0"]
brights = ["#7f8c98", "#d6616b", "#58cd8b", "#ffe37e", "#84cee4", "#b8a1e3", "#59f0ff", "#f2f2f2"]
  