# Nightfox Wezterm Colors
# Style: nordfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nordfox/nightfox_wezterm.toml
[colors]
foreground = "#b9bfca"
background = "#2e3440"
cursor_bg = "#b9bfca"
cursor_border = "#b9bfca"
cursor_fg = "#2e3440"
selection_bg = "#3e4655"
selection_fg = "#b9bfca"
ansi = ["#3b4252", "#bf616a", "#a3be8c", "#ebcb8b", "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0"]
brights = ["#465780", "#d06f79", "#b1d196", "#f0d399", "#8cafd2", "#c895bf", "#93ccdc", "#e7ecf4"]
  